### ISSUE TITLE
ArgumentException: DTD is prohibited in this XML document

### ISSUE THREAD

**Issue by mnkjadhav** [nunit/nunit-transforms#10]
[TestResult.zip](https://github.com/nunit/nunit-transforms/files/1214306/TestResult.zip)

When run NUnit tests using nunit3-console.exe with transform option, I get below error

NUnit.Engine.NUnitEngineException: The path specified in --result junit-results. xml could not be written to ---> System.ArgumentException: Unable to load transform nunit3-junit.xslt ---> System.Xml.XmlException: For security reasons DTD is prohibited in this XML document. To enable DTD processing set the DtdProcessing property on XmlReaderSettings to Parse and pass the settings into XmlReader.Create method.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseDoctypeDecl()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.Xsl.Xslt.XsltInput.ReadTextNodes()
   at System.Xml.Xsl.Xslt.XsltInput.ReadNextSibling()
   at System.Xml.Xsl.Xslt.XsltInput.FindStylesheetElement()
   at System.Xml.Xsl.Xslt.XsltLoader.LoadDocument()
   at System.Xml.Xsl.Xslt.XsltLoader.LoadStylesheet(XmlReader reader, Boolean include)
   --- End of inner exception stack trace ---
   at NUnit.Engine.Services.XmlTransformResultWriter..ctor(Object[] args)
   at NUnit.Engine.Services.ResultService.GetResultWriter(String format, Object[] args)
   at NUnit.ConsoleRunner.ConsoleRunner.RunTests(TestPackage package, TestFilter filter)
   --- End of inner exception stack trace ---
   at NUnit.ConsoleRunner.ConsoleRunner.RunTests(TestPackage package, TestFilter filter)
   at NUnit.ConsoleRunner.Program.Main(String[] args)

**Comment by ChrisMaddock** [comment]
I agree - but don’t (yet) know enough the security implications to know what to do here.

Sorry - on my phone, or I’d move it now!

**Comment by jnm2** [comment]
@nunit/engine-team Does anyone have a tool that can move this issue?

**Comment by mikkelbu** [comment]
Issue moved to [nunit/nunit-console #473](https://github.com/nunit/nunit-console/issues/473) via [**ZenHub**](https://www.zenhub.com/)

**Comment by jnm2** [comment]
Oh my! 😆
